sudo: enabled
branches:
  only:
  - master
matrix:
  include:
  - language: java
    jdk: oraclejdk8
    addons:
      postgresql: '9.5'
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
    before_script:
    - cd server
    - psql -c "create database gmstest;" -U postgres
    - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'postgres'"
    script:
    - "./gradlew test"
    services:
    - postgresql
    after_success:
    - "./gradlew cobertura coveralls"
  - language: node_js
    node_js: lts/*
    addons:
      apt:
        update: true
        sources:
        - google-chrome
        packages:
        - google-chrome-stable
        - google-chrome-beta
    cache:
      directories:
      - node_modules
    before_script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - cd client
    - npm install -g @angular/cli
    - npm install
    script:
    - npm run testcoverage
    - npm run e2e
    after_success:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: openshift
  domain: gms-api
  app: GMS - API
  deployment_branch: master
  secure: k7NI+Yrk0OJ3tK3WDEeVNKKrrqs7ovAykKWJPCfmkj7jufMpL8pM74O4YYDzXBsrgwXRy8KbJ7iiLMMdNezvnIpdqUf/tBWGKRHgG9z2VqB48gw8Wbfzw99XsIAfsPJdxA+THfpaiowx1X+msbTTJH2IHKIZiYco+1ziuTSn/SQqlsKlqgo/aTq0LzciS6FSUzu5ymOCxqBWWqmYJ6Wbiwj/QQN/QWCF38uIw/3cXZc0NkNWfNgvpfgs/iUD3pI1FXb/8LGzpmCNvQ3rw45W+1x3Tkbt5NwU9Xox2Q0L42orWqKorAvqLW4Iqx8O5gPiBtMw2MWnvwl3KuKt9JiKYHZDiqZ712fFeA7Z/Z+hP5P/Z2TJ1EcnWxpCJy8ou4+rpraq06NQqgiE7cPm0TGJCB8sQDbJ0lL7TjP4KFlvHAzqOVZZxdAxbhlF2/miNwSNccDOl9ktMYF07u+yfFmE/asgbHAMXf/aLh6oIrYW121qdEA+oYRhLc0k+zRbMWt3me2YjqMicF37qJybZmZREGa2Gp0hpC7fAGnwZahiRFdASu4QL20rGLV4Kr30xXYGKnLttYQKeI7UhxagQP+H1UjVdXCMwokpMl0v+81O48GW/N1uM6SJ1wFLaCGCAMUJ9NBraw2Bp7xLgR9n0RkmZDWleLnJJZzZph1ye+dh4v0=
env:
  global:
    # username
    secure: FUWZYZJrslSBX2TOrs2Ul7ihCw/FGOzqEoblmZ8QvvKCOpDIOg+AGwnCj61eiFLTJD6S5zeVU4COSjRi7cNfDpGgITOcTRcUE8wceF/bRIJo6J8E3zSYlsX7sCHKEKS2X3UQKn6vDtHotBuxqFOiz/yedwYNWWZVuFn1zavuuz9+us0oWWoEFwzUJQkZm++7OMj1PbTcgmPdvwSqSp5hPfuOgidKrKEORoNtnGjnYtahNzpE39EmdIvWp4HexEr8vraTAvyplHWG7K+M9mg/3ktCtr4bSLHfXsV1FAQyieLBwopeDycorRZqDus3BJXFXUIXL9yiMKlieK8gPWFLcRvU6r6kS+2ttPZtzqlGDd9iOfxVPdoNHwoymgENk2GCAsxT6Pr+uiK9mR5fs2s+MqRAZWbFci+3d7KDAC0hlvIz35oLkb8zD3p9g0aiXRzXPpPgwOkLKrBqzdA04o5HorE+ktJBzBMCfAKOrhtTdpObjcZq+gB2nwcrbqYQE+Yp8MiKMH4kKHK3YT3IhMDuf6KzDPGjmbuLTU4wXQd6PYe1e1ckNIuM+jFVjORv6A2+Um8lXfEWhf88YotJnFIsKgDy1qI6uvmV30SowqlgCfBnDP7tQrKYeVMNZ9ubMdwMHmaiswDjJNuwYHzTU1IzrWJUtNYHEGPMvBafg0NIOFs=
