sudo: enabled
branches:
  only:
  - master
matrix:
  include:
  - language: java
    jdk: oraclejdk8
    addons:
      postgresql: '9.5'
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
    before_script:
    - cd server
    - psql -c "create database gmstest;" -U postgres
    - sudo -u postgres psql -c "ALTER ROLE postgres WITH password 'postgres'"
    script:
    - "./gradlew test"
    services:
    - postgresql
    after_success:
    - "./gradlew cobertura coveralls"
  - language: node_js
    node_js: lts/*
    addons:
      apt:
        update: true
        sources:
        - google-chrome
        packages:
        - google-chrome-stable
        - google-chrome-beta
    cache:
      directories:
      - node_modules
    before_script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - cd client
    - npm install -g @angular/cli
    - npm install
    script:
    - npm run testcoverage
    - npm run e2e
    after_success:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  - provider: openshift
    user: lealceldeiro
    password:
      secure: Pcp4Q45XUbqwUZl7zl6aGneMppqVcKvltieeMuas8lZeqDyBPAr4nRvcXrTX1WI24EsAO/0F4Or2DbSg0ErmYXKzbtk9/cFraGyli4lnEFqwnN7sMNk5BcpjjyUr9MPHDA2PY5B4tc6VQdYErY72hwRYcAv0m4+6u9OLtPEbbr8qY5lSpYiLDjUewb03pkeeqaWtHFNkBcy1ZehrRxtu9Jsd3UnkkVBwUZNedXUY6bEnUMjV6qmsgUDDw3IV5HEPzpzxiUCTx96cbQKtxK5GG/Of4kvSzBt7c2n12pjlW2fVUUL8qcof86dgHvOXU0g3Zb/8Lizb/lBLS+Q3oUNGBidMYglxY97u60Ve98Jjvt5ixB+Sj5aDePBZaNotTFPkvtHd6SJuXeW6EqKsA+lKmUtBRcoOmkD9ZYPaA/3Vm/Oetrgk1+LP14kzdGRgBbRarHyjtGLUImdAwPQeh0ko3vVy1AcF1Fc7/CIrZw53ll9WXVw6Rd2Gm5P9ntZpZP4x05h2fdrkCVCtuMixaygIljEZTYzsoHGKnaIDwsy7kpicU1h9Ysxd9xcaXJrdZwTbnzzufcZMuDPA6zP9pfmCvGU/SDuXElgFx5GtwqMulYeQE2esG/IJr3pIn4bnmK5hW2zV1TedNdnHu4/BulNKMERWGpTU0eguFu8DnMLVGa0=
    app: gms
    domain: gms
    on:
      repo: lealceldeiro/gms
      branch: master
      java: 'oraclejdk8'
      node_js: 'lts/*'
